// libs/angular/desktop/profile/src/lib/components/avatar-selector/avatar-selector.component.ts
import { ChangeDetectionStrategy, Component, inject, input, output } from '@angular/core';

import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatDialog } from '@angular/material/dialog';

import { ImageSelectorComponent } from '@bookapp/angular/ui-desktop';
import { UPLOAD_FOLDERS } from '@bookapp/shared/constants';
import { ProfileForm, User } from '@bookapp/shared/interfaces';

@Component({
  selector: 'bookapp-avatar-selector',
  imports: [MatCardModule, MatButtonModule],
  templateUrl: './avatar-selector.component.html',
  styleUrls: ['./avatar-selector.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AvatarSelectorComponent {
  readonly user = input<User>();

  readonly avatarSaved = output<ProfileForm>();

  readonly #dialog = inject(MatDialog);

  showSelector() {
    const dialogRef = this.#dialog.open(ImageSelectorComponent, {
      width: '300px',
      data: { folder: UPLOAD_FOLDERS.AVATARS },
    });

    dialogRef.afterClosed().subscribe((avatar) => {
      if (avatar) {
        this.avatarSaved.emit({ id: this.user().id, user: { avatar } });
      }
    });
  }
}

<div class="avatar-selector">
  <mat-card>
    <img
      [src]="user.avatar ? user.avatar : '/assets/images/no-avatar.svg'"
      alt="avatar"
      data-test="avatar"
    />
  </mat-card>
  <button mat-raised-button color="primary" (click)="showSelector()" data-test="showSelector">
    Change Avatar
  </button>
</div>

// libs/react/pages/profile/src/lib/AvatarSelector/AvatarSelector.tsx
import { memo } from 'react';

import Button from '@mui/material/Button';
import Card from '@mui/material/Card';

import { ImageSelector, useImageSelector } from '@bookapp/react/ui';
import { UPLOAD_FOLDERS } from '@bookapp/shared/constants';
import { User } from '@bookapp/shared/interfaces';

import { StyledAvatarSelector } from './StyledAvatarSelector';

export interface AvatarSelectorProps {
  user: User;
  onSave: (user: Partial<User>) => void;
}

export const AvatarSelector = ({ user, onSave }: AvatarSelectorProps) => {
  const { isImageSelectorOpened, showImageSelector, hideImageSelector } = useImageSelector();

  const onAvatarUpload = (publicUrl: string) => {
    onSave({ avatar: publicUrl });
  };

  return (
    <StyledAvatarSelector>
      <Card>
        <img
          src={user.avatar ? user.avatar : '/images/no-avatar.svg'}
          alt="avatar"
          data-testid="avatar"
        />
      </Card>
      <Button
        variant="contained"
        color="primary"
        onClick={showImageSelector}
        data-testid="showSelector"
      >
        Change Avatar
      </Button>
      <ImageSelector
        open={isImageSelectorOpened}
        onImageUpload={onAvatarUpload}
        onClose={hideImageSelector}
        folder={UPLOAD_FOLDERS.AVATARS}
      />
    </StyledAvatarSelector>
  );
};

export default memo(AvatarSelector);
