// libs/react/ui/src/lib/BooksList/BooksList.tsx
import React from 'react';
import { Link } from 'react-router-dom';

import Card from '@material-ui/core/Card';
import Rating from '@material-ui/lab/Rating';

import { Book } from '@bookapp/shared/interfaces';

import { InfiniteScroll } from '../InfiniteScroll';
import { LazyImage } from '../LazyImage';
import { useBooksListStyles } from './useBooksListStyles';

export interface BooksListProps {
  books: Book[];
  onBookRate: ({ bookId: string, rate: number }) => void;
  onLoadMore: () => void;
}

export const BooksList = ({ books = [], onBookRate, onLoadMore }: BooksListProps) => {
  const classes = useBooksListStyles();

  return (
    <div className={classes.root}>
      <InfiniteScroll onLoadMore={onLoadMore}>
        {books.map((book) => (
          <div key={book._id} className="list-item-wrapper" data-testid="list-item">
            <Card className="list-item">
              <div className="cover">
                <Link to={book.paid ? '/books/buy/' + book.url : '/books/browse/' + book.url}>
                  <LazyImage
                    src={book.coverUrl}
                    placeholder="/assets/images/nocover.svg"
                    alt={book.title}
                  />
                </Link>
              </div>
              <Link
                className="title"
                to={book.paid ? '/books/buy/' + book.url : '/books/browse/' + book.url}
              >
                {book.title}
              </Link>
              <span className="author">by {book.author}</span>
              {book.paid && <div>{book.price}</div>}
              <Rating
                name="rating"
                value={book.rating}
                // tslint:disable-next-line: jsx-no-lambda
                onChange={(_, value) => {
                  onBookRate({ bookId: book._id, rate: value });
                }}
              />
            </Card>
          </div>
        ))}
      </InfiniteScroll>
    </div>
  );
};

export default BooksList;

// libs/angular/ui/ui-desktop/src/lib/desktop/books-list/books-list.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output
} from '@angular/core';

import { Book } from '@bookapp/shared';

@Component({
  selector: 'bookapp-books-list',
  templateUrl: './books-list.component.html',
  styleUrls: ['./books-list.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class BooksListComponent {
  @Input() books: Book[];
  @Output() bookRated = new EventEmitter<{ bookId: string; rate: number }>();
}

<div *ngFor="let book of books"
     class="list-item-wrapper">
  <mat-card class="list-item">
    <div class="cover">
      <a routerLink="{{ book.paid ? '/books/buy/' + book.url : '/books/browse/' + book.url }}"
         [queryParams]="{ bookId: book.id }">
        <img [src]="book.coverUrl ? book.coverUrl : '/assets/images/nocover.svg'"
             [alt]="book.title">
      </a>
    </div>
    <a class="title"
       routerLink="{{ book.paid ? '/books/buy/' + book.url : '/books/browse/' + book.url }}"
       [queryParams]="{ bookId: book.id }">
      {{ book.title }}
    </a>
    <span class="author">by {{ book.author }}</span>
    <div *ngIf="book.paid">{{ book.price | currency: 'USD': 'symbol-narrow' }}</div>
    <bookapp-rating [ngModel]="book.rating"
                    (ngModelChange)="bookRated.emit({bookId: book._id, rate: $event})"></bookapp-rating>
  </mat-card>
</div>
