// libs/react/guards/src/lib/RolesGuard.tsx
import React, { ReactElement, useEffect } from 'react';
import { RouteProps } from 'react-router';
import { Navigate, Route } from 'react-router-dom';

import { isNil } from 'lodash';

import { store } from '@bookapp/react/core';
import { useAuth } from '@bookapp/react/data-access';
import { AUTH_TOKEN } from '@bookapp/shared/constants';
import { User } from '@bookapp/shared/interfaces';

interface Props extends RouteProps {
  roles: string[];
}

const hasRights = (user: User | null, roles: string[]) =>
  !isNil(user) && user.roles.some((role) => roles.includes(role));

export const RolesGuard: React.FC<Props> = ({ roles, ...props }): ReactElement | null => {
  const accessToken = store.get(AUTH_TOKEN);
  const { getMe, me, fetchingMe } = useAuth();

  useEffect(() => {
    console.log('roles guard effect');
    if (!isNil(accessToken) && isNil(me)) {
      getMe();
    }
  }, []);

  if (isNil(accessToken)) {
    return <Navigate to="/auth" />;
  }

  if (!isNil(me) && !hasRights(me, roles)) {
    return <Navigate to="/" />;
  }

  if (!isNil(me) && hasRights(me, roles)) {
    return <Route {...props} />;
  }

  if (fetchingMe) {
    return null;
  }

  return null;
};

// libs/angular/shared/src/lib/guards/roles.guard.ts
import { inject } from '@angular/core';
import { ActivatedRouteSnapshot } from '@angular/router';

import { RouterExtensions, StoragePlatformService, StoreService } from '@bookapp/angular/core';
import { AuthService } from '@bookapp/angular/data-access';
import { AUTH_TOKEN } from '@bookapp/shared/constants';

import { of } from 'rxjs';
import { catchError, filter, map, switchMap, take } from 'rxjs/operators';

export function rolesGuard(route: ActivatedRouteSnapshot) {
  const authService = inject(AuthService);
  const routerExtensions = inject(RouterExtensions);
  const storeService = inject(StoreService);
  const storagePlatformService = inject(StoragePlatformService);
  const roles = route.data['roles'];

  const waitForUserAndCheckAccess = (roles: string[]) => {
    return authService.fetchMe().pipe(
      map(({ data }) => data.me),
      filter((user) => !!user),
      map((user) => {
        if (!user.roles.some((role) => roles.includes(role))) {
          routerExtensions.navigate(['']);
          return false;
        }

        return true;
      }),
      take(1)
    );
  };

  const accessToken = storeService.get(AUTH_TOKEN);
  const refreshToken = storagePlatformService.getItem(AUTH_TOKEN);

  if (accessToken) {
    return waitForUserAndCheckAccess(roles);
  }

  if (!accessToken && refreshToken) {
    return authService.refreshTokens().pipe(
      switchMap(() => waitForUserAndCheckAccess(roles)),
      catchError(() => of(false))
    );
  }

  this.routerExtensions.navigate(['auth'], {
    // for nativescript
    clearHistory: true,
    transition: {
      name: 'flip',
      duration: 300,
      curve: 'linear',
    },
  });

  return false;
}
