// libs/angular/desktop/passkeys/src/lib/components/passkey/passkey.component.ts
import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';

import { Passkey, PasskeyProvidersMetadata } from '@bookapp/shared/interfaces';

@Component({
  selector: 'bookapp-passkey',
  imports: [MatButtonModule, MatIconModule, MatTooltipModule, DatePipe],
  templateUrl: './passkey.component.html',
  styleUrls: ['./passkey.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PasskeyComponent {
  readonly passkey = input.required<Passkey>();
  readonly passkeyProvidersMetadata = input<Record<string, PasskeyProvidersMetadata>>();
  readonly loading = input(false);

  readonly editPasskey = output<Passkey>();
  readonly deletePasskey = output<Passkey>();
}

@let providerMetadata = passkeyProvidersMetadata()[passkey().aaguid];

<div class="passkey-icon">
  @if (providerMetadata?.icon_light) {
    <img [src]="providerMetadata.icon_light" [alt]="providerMetadata.name" />
  }
</div>

<div class="passkey-info">
  <p class="header">{{ passkey().label }}</p>

  @if (providerMetadata?.name) {
    <p class="cell">{{ providerMetadata.name }}</p>
  }
</div>

<div class="passkey-info">
  <p class="header">Last Used</p>
  <p class="cell">{{ passkey().lastUsedAt | date: 'dd.MM.yyyy HH:mm:ss' }}</p>
</div>

<div class="passkey-actions">
  <button
    type="button"
    matIconButton
    matTooltip="Edit Passkey"
    [disabled]="loading()"
    (click)="editPasskey.emit(passkey())"
    data-test="edit"
  >
    <mat-icon>edit</mat-icon>
  </button>

  <button
    type="button"
    matIconButton
    matTooltip="Delete Passkey"
    [disabled]="loading()"
    (click)="deletePasskey.emit(passkey())"
    data-test="delete"
  >
    <mat-icon>delete</mat-icon>
  </button>
</div>

// libs/react/pages/passkeys/src/lib/Passkey/Passkey.tsx
import Icon from '@mui/material/Icon';
import IconButton from '@mui/material/IconButton';
import Tooltip from '@mui/material/Tooltip';

import { Passkey as IPasskey, PasskeyProvidersMetadata } from '@bookapp/shared/interfaces';
import { formatDate } from '@bookapp/utils/react';

import { StyledPasskey } from './StyledPasskey';

export interface PasskeyProps {
  loading: boolean;
  passkey: IPasskey;
  passkeyProvidersMetadata?: Record<string, PasskeyProvidersMetadata>;
  onEdit: (passkey: IPasskey) => void;
  onDelete: (passkey: IPasskey) => void;
}

export function Passkey({
  loading,
  passkey,
  passkeyProvidersMetadata,
  onEdit,
  onDelete,
}: PasskeyProps) {
  const providerMetadata = passkeyProvidersMetadata?.[passkey.aaguid];

  return (
    <StyledPasskey>
      <div className="passkey-icon">
        {providerMetadata?.icon_light && (
          <img
            src={passkeyProvidersMetadata[passkey.aaguid].icon_light}
            alt={passkeyProvidersMetadata[passkey.aaguid].name}
          />
        )}
      </div>

      <div className="passkey-info">
        <p className="header">{passkey.label}</p>
        {providerMetadata?.name && <p className="cell">{providerMetadata.name}</p>}
      </div>

      <div className="passkey-info">
        <p className="header">Last Used</p>
        <p className="cell">{passkey.lastUsedAt && formatDate(passkey.lastUsedAt)}</p>
      </div>

      <div className="passkey-actions">
        <Tooltip title="Edit Passkey">
          <span>
            <IconButton
              color="default"
              disabled={loading}
              onClick={() => onEdit(passkey)}
              data-testid="edit"
            >
              <Icon color="action">edit</Icon>
            </IconButton>
          </span>
        </Tooltip>

        <Tooltip title="Delete Passkey">
          <span>
            <IconButton
              color="error"
              disabled={loading}
              onClick={() => onDelete(passkey)}
              data-testid="delete"
            >
              <Icon color="error">delete</Icon>
            </IconButton>
          </span>
        </Tooltip>
      </div>
    </StyledPasskey>
  );
}

export default Passkey;
