// libs/react/pages/main/src/lib/Nav/Nav.tsx
import { memo } from 'react';
import { NavLink } from 'react-router-dom';

import Icon from '@mui/material/Icon';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';

import { useLastLogs, useMe } from '@bookapp/react/data-access';
import { categories, navs } from '@bookapp/shared/constants';
import { UserActionsDesc } from '@bookapp/shared/enums';
import { User } from '@bookapp/shared/interfaces';
import { dateToPeriod } from '@bookapp/utils/react';

import { StyledNav } from './StyledNav';

const isAdmin = (user: User) => user.roles.includes('admin');

export const Nav = () => {
  const { me } = useMe();
  const { logs } = useLastLogs(me.id);

  return (
    <StyledNav>
      <List component="nav">
        {isAdmin(me) && (
          <NavLink to="/books/add" className="list-item">
            <ListItem disablePadding>
              <ListItemButton>
                <ListItemIcon>
                  <Icon>add_circle</Icon>
                </ListItemIcon>
                <ListItemText>Add Book</ListItemText>
              </ListItemButton>
            </ListItem>
          </NavLink>
        )}
        <div className="divider" />
        {navs.map((item) => (
          <NavLink key={item.path} to={item.path} className="list-item">
            <ListItem disablePadding>
              <ListItemButton>
                <ListItemIcon>
                  <Icon>{item.icon}</Icon>
                </ListItemIcon>
                <ListItemText>{item.label}</ListItemText>
              </ListItemButton>
            </ListItem>
          </NavLink>
        ))}
      </List>
      <div className="divider" />
      <List component="nav">
        {categories.map((item) => (
          <NavLink key={item.path} to={item.path} className="list-item">
            <ListItem disablePadding>
              <ListItemButton>
                <ListItemIcon>
                  <Icon style={{ color: item.color }}>{item.icon}</Icon>
                </ListItemIcon>
                <ListItemText>{item.label}</ListItemText>
              </ListItemButton>
            </ListItem>
          </NavLink>
        ))}
      </List>
      <div className="divider" />
      <List className="logs" component="ul">
        {logs &&
          logs.map((log) => (
            <div key={log.createdAt} className="list-item">
              <ListItem>
                <ListItemIcon>
                  <Icon>access_time</Icon>
                </ListItemIcon>
                <ListItemText>
                  <p className="action">{UserActionsDesc[log.action]}</p>
                  <p className="footnote">
                    <span>{log.book.title}</span>
                    <br />
                    <span> by {log.book.author}</span>
                  </p>
                  <p className="footnote">{dateToPeriod(log.createdAt)}</p>
                </ListItemText>
              </ListItem>
            </div>
          ))}
      </List>
    </StyledNav>
  );
};

export default memo(Nav);

// libs/angular/desktop/main-layout/src/lib/components/nav/nav.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

import { MatListModule } from '@angular/material/list';

import { DateToPeriodPipe } from '@bookapp/angular/shared';
import { categories, navs } from '@bookapp/shared/constants';
import { ROLES, UserActionsDesc } from '@bookapp/shared/enums';
import { Log, User } from '@bookapp/shared/interfaces';

@Component({
  selector: 'bookapp-nav',
  imports: [MatListModule, RouterLink, RouterLinkActive, DateToPeriodPipe],
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavComponent {
  readonly user = input<User>();
  readonly logs = input<Log[]>();

  readonly navMenu = navs;
  readonly categoryMenu = categories;
  readonly actions = UserActionsDesc;

  readonly isAdmin = computed(() => this.user().roles.includes(ROLES.ADMIN));
}

@if (isAdmin()) {
  <mat-nav-list class="add">
    <a
      mat-list-item
      [routerLink]="['/books/add']"
      routerLinkActive
      #rla="routerLinkActive"
      [activated]="rla.isActive"
    >
      <i matListItemIcon class="material-icons">add_circle</i>
      Add Book
    </a>
  </mat-nav-list>
}

<div class="divider"></div>

<mat-nav-list class="nav">
  @for (link of navMenu; track link.path) {
    <a
      mat-list-item
      [routerLink]="`/${link.path}`"
      routerLinkActive
      #rla="routerLinkActive"
      [activated]="rla.isActive"
    >
      <i matListItemIcon class="material-icons">
        {{ link.icon }}
      </i>
      {{ link.label }}
    </a>
  }
</mat-nav-list>

<div class="divider"></div>

<mat-nav-list class="categories">
  @for (link of categoryMenu; track link.path) {
    <a
      mat-list-item
      [routerLink]="`/${link.path}`"
      routerLinkActive
      #rla="routerLinkActive"
      [activated]="rla.isActive"
    >
      <i matListItemIcon class="material-icons" [style.color]="link.color">
        {{ link.icon }}
      </i>
      {{ link.label }}
    </a>
  }
</mat-nav-list>

<div class="divider"></div>

<mat-list class="logs">
  @for (log of logs(); track log.id) {
    <mat-list-item>
      <i class="material-icons" matListItemIcon>access_time</i>
      <p matListItemTitle class="action">{{ actions[log.action] }}</p>
      <p matListItemLine class="footnote">
        <span>{{ log.book.title }}</span>
        <br />
        <span>by {{ log.book.author }}</span>
      </p>
      <p matListItemLine class="footnote">{{ log.createdAt | dateToPeriod }}</p>
    </mat-list-item>
  }
</mat-list>
