// libs/react/pages/books/view-book/src/lib/BookDetails/BookDetails.tsx
import { memo } from 'react';
import { Link } from 'react-router-dom';

import Icon from '@mui/material/Icon';
import IconButton from '@mui/material/IconButton';
import Rating from '@mui/material/Rating';
import Tooltip from '@mui/material/Tooltip';
import Typography from '@mui/material/Typography';

import { useMe } from '@bookapp/react/data-access';
import { BOOKMARKS, ROLES } from '@bookapp/shared/enums';
import { Book, BookmarkEvent } from '@bookapp/shared/interfaces';
import { formatCurrency } from '@bookapp/utils/react';

import { StyledBookDetails } from './StyledBookDetails';

export interface BookDetailsProps {
  book: Book;
  bookmarks?: string[];
  onBookmarkAdd: (event: BookmarkEvent) => void;
  onBookmarkRemove: (event: BookmarkEvent) => void;
  onBookRate: (event: { bookId: string; rate: number }) => void;
  onPaymentRequest?: (book: Book) => void;
}

export function BookDetails({
  book,
  bookmarks = [],
  onBookmarkAdd,
  onBookmarkRemove,
  onBookRate,
  onPaymentRequest,
}: BookDetailsProps) {
  const { me } = useMe();

  const inFavorites = () => bookmarks.includes(BOOKMARKS.FAVORITES);

  const inWishlist = () => bookmarks.includes(BOOKMARKS.WISHLIST);

  const inMustread = () => bookmarks.includes(BOOKMARKS.MUSTREAD);

  const isAdmin = () => me && me.roles.includes(ROLES.ADMIN);

  const handleFavoritesClick = () => {
    inFavorites()
      ? onBookmarkRemove({
          type: BOOKMARKS.FAVORITES,
          bookId: book.id,
        })
      : onBookmarkAdd({
          type: BOOKMARKS.FAVORITES,
          bookId: book.id,
        });
  };

  const handleWishlistClick = () => {
    inWishlist()
      ? onBookmarkRemove({
          type: BOOKMARKS.WISHLIST,
          bookId: book.id,
        })
      : onBookmarkAdd({
          type: BOOKMARKS.WISHLIST,
          bookId: book.id,
        });
  };

  const handleMustreadClick = () => {
    inMustread()
      ? onBookmarkRemove({
          type: BOOKMARKS.MUSTREAD,
          bookId: book.id,
        })
      : onBookmarkAdd({
          type: BOOKMARKS.MUSTREAD,
          bookId: book.id,
        });
  };

  return (
    <StyledBookDetails>
      <div className="cover">
        <img src={book.coverUrl ? book.coverUrl : '/images/nocover.svg'} alt={book.title} />
        {book.paid && <div>{formatCurrency(book.price)}</div>}
        <Rating
          name="rating"
          value={book.rating}
          onChange={(_, value) => {
            onBookRate({ bookId: book.id, rate: value });
          }}
        />
        <div className="actions">
          {!book.paid && (
            <Link to={`/books/read/${book.url}`} data-testid="read">
              <Tooltip title="Read book">
                <IconButton color="secondary">
                  <Icon color="secondary">book</Icon>
                </IconButton>
              </Tooltip>
            </Link>
          )}
          {book.paid && (
            <Tooltip title="Buy book">
              <IconButton
                color="secondary"
                data-testid="buy"
                onClick={() => onPaymentRequest && onPaymentRequest(book)}
              >
                <Icon color="secondary">credit_card</Icon>
              </IconButton>
            </Tooltip>
          )}
          <Tooltip title={inFavorites() ? 'Remove from Favorites' : 'Add To Favorites'}>
            <IconButton color="secondary" onClick={handleFavoritesClick} data-testid="favorites">
              <Icon color="secondary">{inFavorites() ? 'star' : 'star_border'}</Icon>
            </IconButton>
          </Tooltip>
          {book.paid && (
            <Tooltip title={inWishlist() ? 'Remove from Wishlist' : 'Add to Wishlist'}>
              <IconButton color="secondary" onClick={handleWishlistClick} data-testid="wishlist">
                <Icon color="secondary">{inWishlist() ? 'favorite' : 'favorite_border'}</Icon>
              </IconButton>
            </Tooltip>
          )}
          <Tooltip title={inMustread() ? 'Remove from must read' : 'Add to must read'}>
            <IconButton color="secondary" onClick={handleMustreadClick} data-testid="mustread">
              <Icon color="secondary">{inMustread() ? 'bookmark' : 'bookmark_border'}</Icon>
            </IconButton>
          </Tooltip>
          {isAdmin() && (
            <Link to={`/books/add/${book.url}`} data-testid="edit">
              <Tooltip title="Edit book">
                <IconButton color="secondary">
                  <Icon color="secondary">edit</Icon>
                </IconButton>
              </Tooltip>
            </Link>
          )}
          <div className="view-num">
            <Icon>visibility</Icon>
            <span>{book.views}</span>
          </div>
        </div>
      </div>
      <div className="details">
        <Typography variant="h3" data-testid="title">
          {book.title}
        </Typography>
        <Typography variant="h4">by {book.author}</Typography>
        <div className="toolbar">{book.description || 'No Description'}</div>
      </div>
    </StyledBookDetails>
  );
}

export default memo(BookDetails);

// libs/angular/desktop/books/view-book/src/lib/components/book-details/book-details.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

import { BookDetailsBase } from '@bookapp/angular/base';
import { ROLES } from '@bookapp/shared/enums';
import { Book, User } from '@bookapp/shared/interfaces';

@Component({
  selector: 'bookapp-book-details',
  templateUrl: './book-details.component.html',
  styleUrls: ['./book-details.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BookDetailsComponent extends BookDetailsBase {
  @Input()
  set user(user: User) {
    if (user) {
      this._isAdmin = user.roles.includes(ROLES.ADMIN);
    }
  }

  @Output()
  paymentRequested = new EventEmitter<Book>();

  private _isAdmin: boolean;

  get isAdmin(): boolean {
    return this._isAdmin;
  }
}

<div class="book-view">
  <div class="cover">
    <img [src]="book.coverUrl ? book.coverUrl : '/assets/images/nocover.svg'" [alt]="book.title" />
    <div *ngIf="book.paid">{{ book.price | currency: 'USD':'symbol-narrow' }}</div>
    <bookapp-rating [ngModel]="book.rating" (ngModelChange)="rate($event)"></bookapp-rating>
    <div class="actions">
      <a
        *ngIf="!book.paid"
        routerLink="/books/read/{{ book.url }}"
        mat-icon-button
        matTooltip="Read book"
        color="accent"
        data-test="read"
      >
        <mat-icon>book</mat-icon>
      </a>
      <button
        *ngIf="book.paid"
        type="button"
        mat-icon-button
        matTooltip="Buy book"
        color="accent"
        (click)="paymentRequested.emit(book)"
      >
        <mat-icon>credit_card</mat-icon>
      </button>
      <button
        id="favorites"
        type="button"
        mat-icon-button
        [matTooltip]="inFavorites ? 'Remove from Favorites' : 'Add To Favorites'"
        color="accent"
        data-test="favorites"
        (click)="
          (inFavorites ? bookmarkRemoved : bookmarkAdded).emit({
            type: BOOKMARKS.FAVORITES,
            bookId: book._id
          })
        "
      >
        <mat-icon>{{ inFavorites ? 'star' : 'star_border' }}</mat-icon>
      </button>
      <button
        *ngIf="book.paid"
        id="wishlist"
        type="button"
        mat-icon-button
        [matTooltip]="inWishlist ? 'Remove from Wishlist' : 'Add to Wishlist'"
        color="accent"
        data-test="wishlist"
        (click)="
          (inWishlist ? bookmarkRemoved : bookmarkAdded).emit({
            type: BOOKMARKS.WISHLIST,
            bookId: book._id
          })
        "
      >
        <mat-icon>{{ inWishlist ? 'favorite' : 'favorite_border' }}</mat-icon>
      </button>
      <button
        id="mustread"
        type="button"
        mat-icon-button
        [matTooltip]="inMustread ? 'Remove from must read' : 'Add to must read'"
        color="accent"
        data-test="mustread"
        (click)="
          (inMustread ? bookmarkRemoved : bookmarkAdded).emit({
            type: BOOKMARKS.MUSTREAD,
            bookId: book._id
          })
        "
      >
        <mat-icon>{{ inMustread ? 'bookmark' : 'bookmark_border' }}</mat-icon>
      </button>
      <a
        *ngIf="isAdmin"
        id="edit"
        routerLink="/books/add/{{ book.url }}"
        mat-icon-button
        matTooltip="Edit book"
        color="accent"
      >
        <mat-icon>edit</mat-icon>
      </a>
    </div>
    <div class="view-num">
      <i class="material-icons"> visibility </i>
      <span>{{ book.views }}</span>
    </div>
  </div>
  <div class="details">
    <h3 data-test="title">{{ book.title }}</h3>
    <h4>by {{ book.author }}</h4>
    <div class="toolbar">{{ book.description || 'No Description' }}</div>
  </div>
</div>
