// libs/react/pages/main/src/lib/Footer/Footer.tsx
import React, { memo } from 'react';

import AppBar from '@material-ui/core/AppBar';
import Icon from '@material-ui/core/Icon';
import IconButton from '@material-ui/core/IconButton';
import Toolbar from '@material-ui/core/Toolbar';

import { useFooterStyles } from './useFooterStyles';

export const Footer = () => {
  const classes = useFooterStyles();

  return (
    <AppBar className={classes.appBar} position="fixed" color="primary">
      <Toolbar className={classes.footer}>
        <IconButton>
          <Icon>help</Icon>
        </IconButton>
        <IconButton>
          <Icon>settings</Icon>
        </IconButton>
      </Toolbar>
    </AppBar>
  );
};

export default memo(Footer);

// libs/angular/desktop/main-layout/src/lib/components/footer/footer.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'bookapp-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FooterComponent {}

<mat-toolbar color="primary"
             class="footer">
  <a href="javascript:void(0)"
     mat-icon-button>
    <i class="material-icons">
      help
    </i>
  </a>
  <a href="javascript:void(0)"
     mat-icon-button>
    <i class="material-icons">
      settings
    </i>
  </a>
</mat-toolbar>
