// libs/angular/base/src/lib/books/best-books.ts
import { inject, signal } from '@angular/core';

import { BestBooksService } from '@bookapp/angular/data-access';
import { DEFAULT_LIMIT } from '@bookapp/shared/constants';
import { Book, RateBookEvent } from '@bookapp/shared/interfaces';

import { Observable } from 'rxjs';
import { filter, map, shareReplay, startWith, tap } from 'rxjs/operators';

import { BaseComponent } from '../core/base-component';

export abstract class BestBooksBase extends BaseComponent {
  readonly #booksService = inject(BestBooksService);

  readonly source$ = this.#booksService
    .watchBooks()
    .pipe(shareReplay({ bufferSize: 1, refCount: true }));

  readonly books$: Observable<Book[]> = this.source$.pipe(
    filter(({ data }) => !!data.bestBooks),
    tap(({ data }) => {
      const { rows, count } = data.bestBooks;
      this.hasMoreItems.set(rows.length !== count);
    }),
    map(({ data }) => data.bestBooks.rows)
  );

  readonly loading$: Observable<boolean> = this.source$.pipe(
    startWith({ loading: true }),
    map(({ loading }) => loading),
    tap((loading: boolean) => {
      this.#pending = loading;
    })
  );

  readonly hasMoreItems = signal(false);

  #skip = 0;
  #pending = false;

  loadMore() {
    if (this.#pending) {
      return;
    }

    if (this.hasMoreItems()) {
      this.#skip += DEFAULT_LIMIT;
      this.#booksService.loadMore(this.#skip);
    }
  }

  rate(event: RateBookEvent) {
    this.#booksService.rateBook(event).subscribe();
  }
}

// libs/react/pages/books/best-books/src/lib/BestBooks.tsx
import React, { useRef } from 'react';

import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';

import { useBestBooks } from '@bookapp/react/data-access';
import { BooksList, FullPageSpinner } from '@bookapp/react/ui';
import { DEFAULT_LIMIT } from '@bookapp/shared/constants';
import { ApiResponse, Book } from '@bookapp/shared/interfaces';

import { useBestBooksStyles } from './useBestBooksStyles';

export function BestBooks() {
  const classes = useBestBooksStyles();
  const hasMoreItems = useRef(false);
  const skip = useRef(0);
  const { books, loading, loadMore, rateBook } = useBestBooks();

  const toBooks = (data: ApiResponse<Book>): Book[] => {
    const { rows, count } = data;
    hasMoreItems.current = rows.length < count;

    return rows;
  };

  const onLoadMore = () => {
    if (!hasMoreItems.current || loading) {
      return;
    }

    skip.current += DEFAULT_LIMIT;
    loadMore(skip.current);
  };

  return (
    <>
      {loading && <FullPageSpinner />}
      <div className={classes.root}>
        <Toolbar disableGutters={true}>
          <Typography component="span">List Of The Best</Typography>
        </Toolbar>
        <div className="view-content">
          <BooksList
            books={books && toBooks(books)}
            onLoadMore={onLoadMore}
            onBookRate={rateBook}
          />
        </div>
      </div>
    </>
  );
}

export default BestBooks;
