// libs/angular/desktop/main-layout/src/lib/components/header/header.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

import { userMenu } from '@bookapp/shared/constants';
import { User } from '@bookapp/shared/interfaces';

@Component({
  selector: 'bookapp-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderComponent {
  readonly title = 'Book App';
  readonly userMenu = userMenu;

  @Input() isMobile = false;
  @Input() user: User;

  @Output() toggleSidenav = new EventEmitter<void>();
  @Output() logout = new EventEmitter<void>();

  doToggleSidenav() {
    this.toggleSidenav.emit();
  }

  doLogout() {
    this.logout.emit();
  }
}

<mat-toolbar [class.is-mobile]="isMobile()">
  <button mat-icon-button class="menu-toggler" (click)="doToggleSidenav()">
    <i class="material-icons">menu</i>
  </button>
  <a [routerLink]="['/']" class="brand">
    <i class="material-icons">book</i>
    <span>{{ title }}</span>
  </a>

  @if (user(); as user) {
    <div class="user-menu">
      <button
        matIconButton
        class="theme-switcher"
        matTooltip="Switch Theme"
        [matMenuTriggerFor]="themes"
      >
        @switch (themeMode()) {
          @case ('auto') {
            <mat-icon>brightness_medium</mat-icon>
          }

          @case ('light') {
            <mat-icon>light_mode</mat-icon>
          }

          @case ('dark') {
            <mat-icon>dark_mode</mat-icon>
          }
        }
      </button>

      <mat-menu #themes="matMenu">
        <button
          mat-menu-item
          [class.active]="themeMode() === 'auto'"
          (click)="toggleMode.emit('auto')"
          data-testid="system-theme"
        >
          <mat-icon>brightness_medium</mat-icon>
          <span>System</span>
        </button>

        <button
          mat-menu-item
          [class.active]="themeMode() === 'light'"
          (click)="toggleMode.emit('light')"
          data-testid="light-theme"
        >
          <mat-icon>light_mode</mat-icon>
          <span>Light</span>
        </button>

        <button
          mat-menu-item
          [class.active]="themeMode() === 'dark'"
          (click)="toggleMode.emit('dark')"
          data-testid="dark-theme"
        >
          <mat-icon>dark_mode</mat-icon>
          <span>Dark</span>
        </button>
      </mat-menu>

      <button matButton id="user-menu-toggler" [matMenuTriggerFor]="menu">
        <img
          class="avatar"
          [src]="user.avatar ? user.avatar : '/assets/images/no-avatar.svg'"
          alt="avatar"
        />
        <i class="material-icons">expand_more</i>
      </button>

      <mat-menu #menu="matMenu">
        <span mat-menu-item>{{ user.displayName }}</span>

        <mat-divider />

        @for (item of userMenu; track item.path) {
          <a mat-menu-item [routerLink]="['/', item.path]" routerLinkActive="active">
            <mat-icon>{{ item.icon }}</mat-icon>
            <span>{{ item.label }}</span>
          </a>
        }

        <mat-divider />

        <button mat-menu-item id="logout" type="button" (click)="doLogout()">
          <mat-icon>logout</mat-icon>
          <span>Signout</span>
        </button>
      </mat-menu>
    </div>
  }
</mat-toolbar>

// libs/react/pages/main/src/lib/Header/Header.tsx
import React, { memo, useState } from 'react';
import { Link, NavLink } from 'react-router-dom';

import Button from '@mui/material/Button';
import Divider from '@mui/material/Divider';
import Icon from '@mui/material/Icon';
import IconButton from '@mui/material/IconButton';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import Toolbar from '@mui/material/Toolbar';
import { useColorScheme } from '@mui/material/styles';

import { useAuth, useMe } from '@bookapp/react/data-access';
import { userMenu } from '@bookapp/shared/constants';

import { StyledHeader } from './StyledHeader';

export interface HeaderProps {
  toggleDrawer: () => void;
}

export const Header = ({ toggleDrawer }: HeaderProps) => {
  const { me } = useMe();
  const { logout } = useAuth();
  const { mode, setMode } = useColorScheme();
  const [userMenuAnchorEl, setUserMenuAnchorEl] = useState<null | HTMLElement>(null);
  const [themeMenuAnchorEl, setThemeMenuAnchorEl] = useState<null | HTMLElement>(null);

  const openUserMenu = (event: React.MouseEvent<HTMLButtonElement>) => {
    setUserMenuAnchorEl(event.currentTarget);
  };

  const closeUserMenu = () => {
    setUserMenuAnchorEl(null);
  };

  const openThemeMenu = (event: React.MouseEvent<HTMLButtonElement>) => {
    setThemeMenuAnchorEl(event.currentTarget);
  };

  const closeThemeMenu = () => {
    setThemeMenuAnchorEl(null);
  };

  const handleLogoutClick = () => {
    closeUserMenu();
    logout();
  };

  return (
    <StyledHeader color="primary" position="fixed">
      <Toolbar>
        <IconButton
          className="menu-toggler"
          onClick={toggleDrawer}
          data-testid="toggle-menu"
          size="large"
        >
          <Icon>menu</Icon>
        </IconButton>
        <Link to="/" className="brand">
          <Icon>book</Icon>
          <span>Book App</span>
        </Link>
        {me && (
          <div className="user-menu">
            <IconButton id="theme-switcher" className="theme-switcher" onClick={openThemeMenu}>
              <Icon>
                {mode == 'system'
                  ? 'brightness_medium'
                  : mode == 'light'
                    ? 'light_mode'
                    : 'dark_mode'}
              </Icon>
            </IconButton>
            <Menu
              className="menu"
              anchorEl={themeMenuAnchorEl}
              anchorOrigin={{
                vertical: 'bottom',
                horizontal: 'left',
              }}
              open={Boolean(themeMenuAnchorEl)}
              onClose={closeThemeMenu}
            >
              <MenuItem
                onClick={() => {
                  setMode('system');
                  closeThemeMenu();
                }}
              >
                System
              </MenuItem>
              <MenuItem
                onClick={() => {
                  setMode('light');
                  closeThemeMenu();
                }}
              >
                Light
              </MenuItem>
              <MenuItem
                onClick={() => {
                  setMode('dark');
                  closeThemeMenu();
                }}
              >
                Dark
              </MenuItem>
            </Menu>

            <Button
              id="user-menu"
              className="user-menu-toggler"
              onClick={openUserMenu}
              endIcon={<Icon>expand_more</Icon>}
            >
              <img
                src={me.avatar ? me.avatar : '/images/no-avatar.svg'}
                className="avatar"
                alt="avatar"
              />
              {me.displayName}
            </Button>
            <Menu
              className="menu"
              anchorEl={userMenuAnchorEl}
              anchorOrigin={{
                vertical: 'bottom',
                horizontal: 'left',
              }}
              open={Boolean(userMenuAnchorEl)}
              onClose={closeUserMenu}
            >
              {[...userMenu, { label: 'Passkeys', path: 'passkeys' }].map((item) => (
                <NavLink key={item.path} to={item.path} className="link">
                  <MenuItem onClick={closeUserMenu}>{item.label}</MenuItem>
                </NavLink>
              ))}
              <Divider />
              <div className="link">
                <MenuItem onClick={handleLogoutClick}>Signout</MenuItem>
              </div>
            </Menu>
          </div>
        )}
      </Toolbar>
    </StyledHeader>
  );
};

export default memo(Header);
