// libs/angular/ui/ui-desktop/src/lib/books-list/books-list.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from '@angular/core';

import { Book } from '@bookapp/shared/interfaces';

@Component({
  selector: 'bookapp-books-list',
  templateUrl: './books-list.component.html',
  styleUrls: ['./books-list.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BooksListComponent {
  @Input() books: Book[];
  @Input() hasMoreItems: boolean;

  @Output() bookRated = new EventEmitter<{ bookId: string; rate: number }>();
  @Output() loadMore = new EventEmitter<void>();

  handleScrollChange() {
    if (!this.hasMoreItems) {
      return;
    }

    this.loadMore.emit();
  }
}

<bookapp-infinite-scroll (scrolled)="handleScrollChange()">
  @for (book of books(); track book.id) {
    <div class="list-item-wrapper" data-test="list-item">
      <mat-card class="list-item">
        <div class="cover">
          <a
            routerLink="{{ book.paid ? `/books/buy/${book.url}` : `/books/browse/${book.url}` }}"
            [queryParams]="{ bookId: book.id }"
          >
            <img
              src="/assets/images/nocover.svg"
              [bookappLazyImage]="book.coverUrl ? book.coverUrl : '/assets/images/nocover.svg'"
              [alt]="book.title"
            />
          </a>
        </div>
        <a
          class="title"
          routerLink="{{ book.paid ? `/books/buy/${book.url}` : `/books/browse/${book.url}` }}"
          [queryParams]="{ bookId: book.id }"
        >
          {{ book.title }}
        </a>
        <span class="author">by {{ book.author }}</span>

        @if (book.paid) {
          <div class="price">{{ book.price | currency: 'USD' : 'symbol-narrow' }}</div>
        }

        <bookapp-rating
          [ngModel]="book.rating"
          (ngModelChange)="bookRated.emit({ bookId: book.id, rate: $event })"
        />
      </mat-card>
    </div>
  }
</bookapp-infinite-scroll>

// libs/react/ui/src/lib/BooksList/BooksList.tsx
import React from 'react';
import { Link } from 'react-router-dom';

import Card from '@material-ui/core/Card';
import Rating from '@material-ui/lab/Rating';

import { Book } from '@bookapp/shared/interfaces';

import { InfiniteScroll } from '../InfiniteScroll';
import { LazyImage } from '../LazyImage';
import { useBooksListStyles } from './useBooksListStyles';

export interface BooksListProps {
  books: Book[];
  hasMoreItems: boolean;
  onBookRate: ({ bookId: string, rate: number }) => void;
  onLoadMore: () => void;
}

export const BooksList = ({ books = [], hasMoreItems, onBookRate, onLoadMore }: BooksListProps) => {
  const classes = useBooksListStyles();

  const loadMore = () => {
    if (!hasMoreItems) {
      return;
    }

    onLoadMore();
  };

  return (
    <div className={classes.root}>
      <InfiniteScroll onLoadMore={loadMore}>
        {books.map((book) => (
          <div key={book._id} className="list-item-wrapper" data-testid="list-item">
            <Card className="list-item">
              <div className="cover">
                <Link to={book.paid ? '/books/buy/' + book.url : '/books/browse/' + book.url}>
                  <LazyImage
                    src={book.coverUrl}
                    placeholder="/assets/images/nocover.svg"
                    alt={book.title}
                  />
                </Link>
              </div>
              <Link to={book.paid ? '/books/buy/' + book.url : '/books/browse/' + book.url}>
                {book.title}
              </Link>
              <span className="author">by {book.author}</span>
              {book.paid && <div>{book.price}</div>}
              <Rating
                name="rating"
                value={book.rating}
                // tslint:disable-next-line: jsx-no-lambda
                onChange={(_, value) => {
                  onBookRate({ bookId: book._id, rate: value });
                }}
              />
            </Card>
          </div>
        ))}
      </InfiniteScroll>
    </div>
  );
};

export default BooksList;
